// FunMeter/FaceRecognition/src-vue-original/components/GlobalConfirm.vue
<script setup lang="ts">
import { computed, ref, nextTick, onMounted } from "vue";
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
} from "@/components/ui/alert-dialog";
import { currentConfirm, resolveCurrentConfirm } from "@/stores/confirmStore";

const active = computed(() => currentConfirm.value);
const closingReason = ref<null | "confirm" | "cancel">(null);

function handleOpenChange(next: boolean) {
  if (!next && active.value) {
    nextTick(() => {
      resolveCurrentConfirm(closingReason.value === "confirm");
      closingReason.value = null;
    });
  }
}

function handleConfirm() {
  closingReason.value = "confirm";
}

function handleCancel() {
  closingReason.value = "cancel";
}
</script>

<template>
  <AlertDialog :open="!!active" @update:open="handleOpenChange">
    <AlertDialogContent v-if="active" :disableOutsidePointerEvents="false">
      <AlertDialogHeader>
        <AlertDialogTitle>{{ active.options.title }}</AlertDialogTitle>
        <AlertDialogDescription v-if="active.options.description">
          {{ active.options.description }}
        </AlertDialogDescription>
      </AlertDialogHeader>
      <AlertDialogFooter>
        <AlertDialogCancel @click="handleCancel">
          {{ active.options.cancelText }}
        </AlertDialogCancel>
        <AlertDialogAction @click="handleConfirm">
          {{ active.options.confirmText }}
        </AlertDialogAction>
      </AlertDialogFooter>
    </AlertDialogContent>
  </AlertDialog>
</template>

// FunMeter/frontend/components/modals/GlobalConfirm.tsx
// components/modals/GlobalConfirm.tsx
// Port dari src-vue-original/components/GlobalConfirm.vue

"use client";

import React, { useEffect } from "react";
import { Button } from "@/components/ui/button";
import { Icon } from "@/components/common/Icon";
import { useConfirmDialogState } from "@/components/providers/ConfirmDialogProvider";
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
} from "@/components/ui/alert-dialog";

export function GlobalConfirm() {
  const { currentConfirm, resolveCurrentConfirm } = useConfirmDialogState();

  if (!currentConfirm) return null;

  const { options } = currentConfirm;

  const handleConfirm = () => {
    resolveCurrentConfirm(true);
  };

  const handleCancel = () => {
    resolveCurrentConfirm(false);
  };

  // ESC key handler
  useEffect(() => {
    if (!currentConfirm) return;
    const handleEsc = (e: KeyboardEvent) => {
      if (e.key === 'Escape') {
        handleCancel();
      }
    };
    window.addEventListener('keydown', handleEsc);
    return () => window.removeEventListener('keydown', handleEsc);
  }, [currentConfirm]);

  return (
    <AlertDialog open={!!currentConfirm} onOpenChange={(open) => { if (!open) resolveCurrentConfirm(false); }}>
      <AlertDialogContent>
        <AlertDialogHeader>
          <div className="flex items-center justify-between gap-4">
            <div>
              <AlertDialogTitle>{options.title}</AlertDialogTitle>
              {options.description && (
                <AlertDialogDescription>{options.description}</AlertDialogDescription>
              )}
            </div>
            <Button
              type="button"
              variant="ghost"
              size="icon"
              onClick={handleCancel}
              aria-label="Close"
            >
              <Icon name="X" className="h-4 w-4" />
            </Button>
          </div>
        </AlertDialogHeader>
        <AlertDialogFooter>
          <AlertDialogCancel onClick={handleCancel}>
            {options.cancelText}
          </AlertDialogCancel>
          <AlertDialogAction onClick={handleConfirm}>
            {options.confirmText}
          </AlertDialogAction>
        </AlertDialogFooter>
      </AlertDialogContent>
    </AlertDialog>
  );
}
