// FunMeter/FaceRecognition/src-vue-original/components/AppSidebar.vue
<script setup lang="ts">
import type { SidebarProps } from "@/components/ui/sidebar";
import type { Component } from "vue";
import { computed, h, inject } from "vue";
import { useI18n } from "@/i18n";
import Icon from "@/components/Icon.vue";

import RouterMenuButton from "@/components/RouterMenuButton.vue";
import { isExternalLink } from "@/utils/link";

// Props...
const props = withDefaults(
  defineProps<
    SidebarProps & {
      navItems?: Array<{
        name?: string;
        to: string;
        icon?: string | Component;
        labelKey?: string;
        labelFallback?: string;
      }>;
    }
  >(),
  { side: "left", variant: "sidebar", collapsible: "icon" }
);

const { t } = useI18n();
const ft = (path:any, fallback:any, values:any) => t(`aside.${path}`, fallback, values);
const settings = inject<any>("settings", null);
const auth = inject<any>("auth", null);

const isAdmin = (it: any) => String(it?.to || "").startsWith("/admin");
const baseNav = computed(() => (props.navItems || []).filter((it) => !isAdmin(it)));
const adminNav = computed(() => (props.navItems || []).filter(isAdmin));

function RenderIcon({ icon }: { icon?: string | Component }) {
  if (!icon) return null as any;
  if (typeof icon === "string") {
    return h(Icon, { name: icon, class: "h-6 w-6" });
  }
  return h(icon as Component, { class: "h-6 w-6" });
}

const displayName = computed(() => {
  const u = auth?.state?.user;
  return String(u?.username || u?.name || "").trim();
});

function getInitials(raw?: string) {
  const name = String(raw || "")
    .replace(/_/g, " ") // underscore -> spasi
    .replace(/\s+/g, " ") // rapihin spasi ganda
    .trim();

  if (!name) return "??";

  const parts = name.split(" ").filter(Boolean);
  const first = (s: string) => s.charAt(0)?.toUpperCase() || "";

  // kalau ada >= 2 kata, ambil 2 huruf awal dari dua kata pertama
  if (parts.length >= 2) return first(parts[0]) + first(parts[1]);

  // kalau 1 kata, ambil 1 huruf awal
  return first(parts[0]);
}

const initials = computed(() => getInitials(displayName.value));
</script>

<template>
  <Sidebar v-bind="props">
    <SidebarRail />

    <SidebarHeader>
      <SidebarMenuButton
        size="lg"
        class="data-[state=open]:bg-sidebar-accent data-[state=open]:text-sidebar-accent-foreground">
        <Avatar class="place-items-center rounded-lg">
          <AvatarFallback class="ti ti-mood-check bg-primary text-primary-foreground text-xl" />
        </Avatar>

        <div class="grid flex-1 text-left text-sm leading-tight">
          <span class="truncate font-semibold">{{ ft("brand.title", "Absensi Wajah") }}</span>
        </div>
      </SidebarMenuButton>
    </SidebarHeader>
    <SidebarContent>
      <!-- MAIN -->
      <SidebarGroup v-if="baseNav.length">
        <SidebarGroupLabel>{{ ft("groups.main", "Menu Utama") }}</SidebarGroupLabel>
        <SidebarGroupContent>
          <SidebarMenu>
            <SidebarMenuItem v-for="item in baseNav" :key="item.to">
              <template v-if="!isExternalLink(item.to)">
                <RouterMenuButton
                  :to="item.to"
                  :tooltip="t(item.labelKey || '', item.labelFallback || String(item.name || ''))">
                  <RenderIcon :icon="item.icon" />
                  <span class="truncate">
                    {{ t(item.labelKey || "", item.labelFallback || String(item.name || "")) }}
                  </span>
                </RouterMenuButton>
              </template>
              <template v-else>
                <SidebarMenuButton
                  as-child
                  :tooltip="t(item.labelKey || '', item.labelFallback || String(item.name || ''))">
                  <a :href="item.to" target="_blank" rel="noopener noreferrer">
                    <RenderIcon :icon="item.icon" />
                    <span class="truncate">
                      {{ t(item.labelKey || "", item.labelFallback || String(item.name || "")) }}
                    </span>
                  </a>
                </SidebarMenuButton>
              </template>
            </SidebarMenuItem>
          </SidebarMenu>
        </SidebarGroupContent>
      </SidebarGroup>

      <!-- ADMIN -->
      <SidebarGroup v-if="adminNav.length">
        <SidebarGroupLabel>{{ ft("groups.admin", "Admin") }}</SidebarGroupLabel>
        <SidebarGroupContent>
          <SidebarMenu>
            <SidebarMenuItem v-for="item in adminNav" :key="item.to">
              <RouterMenuButton
                :to="item.to"
                :tooltip="t(item.labelKey || '', item.labelFallback || String(item.name || ''))">
                <RenderIcon :icon="item.icon" />
                <span class="truncate">
                  {{ t(item.labelKey || "", item.labelFallback || String(item.name || "")) }}
                </span>
              </RouterMenuButton>
            </SidebarMenuItem>
          </SidebarMenu>
        </SidebarGroupContent>
      </SidebarGroup>
    </SidebarContent>

    <SidebarFooter>
      <SidebarMenu>
        <SidebarMenuItem>
          <SidebarMenuButton
            as-child
            @click="settings?.openModal?.()"
            :tooltip="ft('actions.openSettings', 'Buka Pengaturan')">
            <button type="button">
              <Icon name="Settings" class="h-6 w-6" />
              <span class="truncate">{{ ft("actions.openSettings", "Buka Pengaturan") }}</span>
            </button>
          </SidebarMenuButton>
        </SidebarMenuItem>
      </SidebarMenu>

      <template v-if="auth?.state?.user">
        <DropdownMenu>
          <DropdownMenuTrigger as-child>
            <SidebarMenuButton
              size="lg"
              class="data-[state=open]:bg-sidebar-accent data-[state=open]:text-sidebar-accent-foreground">
              <Avatar class="place-items-center rounded-lg">
                <AvatarFallback class="bg-primary text-primary-foreground text-sm">{{ initials }}</AvatarFallback>
              </Avatar>

              <div class="grid flex-1 text-left text-sm leading-tight">
                <span class="truncate font-semibold">
                  {{ auth?.state?.user?.username || auth?.state?.user?.name }}
                </span>
              </div>
              <Icon name="ChevronsUpDown" class="size-4" />
            </SidebarMenuButton>
          </DropdownMenuTrigger>

          <DropdownMenuContent
            class="w-[var(--reka-dropdown-menu-trigger-width)] min-w-56 rounded-lg"
            align="start"
            :side-offset="4">
            <DropdownMenuLabel>
              <div class="flex items-center gap-2 px-1 py-1.5 text-left text-sm">
                <Avatar class="place-items-center rounded-lg">
                  <AvatarFallback class="bg-primary text-primary-foreground text-sm">{{ initials }}</AvatarFallback>
                </Avatar>

                <div class="grid flex-1 text-left text-sm leading-tight">
                  <span class="truncate font-semibold">
                    {{ auth?.state?.user?.username || auth?.state?.user?.name }}
                  </span>
                </div>
              </div>
            </DropdownMenuLabel>
            <DropdownMenuSeparator />
            <DropdownMenuItem class="gap-2 p-2" @click="auth?.logout?.()">
              <Icon name="LogOut" class="size-4" />
              <div class="font-medium">{{ t("auth.menu.logout", "Keluar") }}</div>
            </DropdownMenuItem>
          </DropdownMenuContent>
        </DropdownMenu>
      </template>
      <template v-else>
        <SidebarMenuItem class="mt-2">
          <SidebarMenuButton
            size="xs"
            class="data-[state=open]:bg-sidebar-accent data-[state=open]:text-sidebar-accent-foreground"
            @click="auth?.openModal?.('login')">
            <Icon name="LogIn" class="h-4 w-4" />
            <span class="truncate font-semibold">{{ t("auth.actions.login", "Masuk") }}</span>
          </SidebarMenuButton>
        </SidebarMenuItem>
      </template>
    </SidebarFooter>
  </Sidebar>
</template>

// FunMeter/frontend/components/layout/AppSidebar.tsx
// components/layout/AppSidebar.tsx
// Port dari src-vue-original/components/AppSidebar.vue

"use client";

import React from "react";
import Link from "next/link";
import { usePathname } from "next/navigation";
import { useAuth } from "@/components/providers/AuthProvider";
import { useI18n } from "@/components/providers/I18nProvider";
import { useSettings } from "@/components/providers/SettingsProvider";
import { Icon } from "@/components/common/Icon";
import { Button } from "@/components/ui/button";
import { cn } from "@/lib/utils";
import { useSidebar } from "@/components/ui/sidebar";

interface NavItem {
  name: string;
  to: string;
  icon: string;
  labelKey?: string;
  labelFallback: string;
}

interface AppSidebarProps {
  navItems: NavItem[];
}

function getInitials(name?: string): string {
  const cleanName = String(name || "")
    .replace(/_/g, " ") // underscore -> spasi
    .replace(/\s+/g, " ") // rapihin spasi ganda
    .trim();

  if (!cleanName) return "??";

  const parts = cleanName.split(" ").filter(Boolean);
  const first = (s: string) => s.charAt(0)?.toUpperCase() || "";

  // kalau ada >= 2 kata, ambil 2 huruf awal dari dua kata pertama
  if (parts.length >= 2) return first(parts[0]) + first(parts[1]);

  // kalau 1 kata, ambil 1 huruf awal
  return first(parts[0]);
}

function isExternalLink(url: string): boolean {
  return /^https?:\/\//.test(url);
}

export function AppSidebar({ navItems }: AppSidebarProps) {
  const pathname = usePathname();
  const { user, openModal, logout } = useAuth();
  const { t } = useI18n();
  const { openModal: openSettingsModal } = useSettings();
  const { isOpen, setIsOpen, isMobile } = useSidebar();

  const ft = (path: string, fallback: string, values?: Record<string, unknown>) => 
    t(`aside.${path}`, fallback, values);

  const isAdmin = (item: NavItem) => item.to.startsWith("/admin");
  const baseNav = navItems.filter((item) => !isAdmin(item));
  const adminNav = navItems.filter(isAdmin);

  const displayName = user?.username || user?.name || "";
  const initials = getInitials(displayName);

  return (
    <>
      {/* Overlay untuk mobile */}
      {isMobile && isOpen && (
        <div 
          className="fixed inset-0 z-40 bg-black/50 lg:hidden animate-in fade-in duration-300"
          onClick={() => setIsOpen(false)}
          aria-hidden="true"
        />
      )}
      
      {/* Sidebar */}
      <div className={cn(
        "flex h-svh flex-col border-r bg-sidebar text-sidebar-foreground overflow-hidden transition-all duration-300 ease-in-out will-change-[width,transform]",
        // Mobile: fixed position with slide animation
        isMobile ? [
          "fixed top-0 left-0 z-50",
          isOpen ? "translate-x-0 w-64" : "-translate-x-full w-64"
        ] : [
          // Desktop: sticky position with width animation
          "sticky top-0 pl-0.5",
          isOpen ? "w-64" : "w-14"
        ]
      )}>
      {/* Header */}
      <div className={cn(
        "flex h-16 items-center border-b transition-all duration-300 ease-in-out",
        isOpen ? "px-4" : "justify-center px-0"
      )}>
        <div className={cn(
          "flex items-center transition-all duration-300 ease-in-out",
          isOpen ? "gap-2" : "gap-0"
        )}>
          <div className="flex h-8 w-8 items-center justify-center rounded-lg bg-primary text-primary-foreground">
            <Icon name="Smile" className={cn("transition-all", isOpen ? "h-4 w-4" : "h-5 w-5")} />
          </div>
          <span
            className={cn(
              "font-semibold truncate transition-all duration-300 ease-in-out will-change-[opacity,width]",
              isOpen ? "opacity-100 w-auto" : "opacity-0 w-0 overflow-hidden"
            )}
            aria-hidden={!isOpen}
          >
            {ft("brand.title", "Absensi Wajah")}
          </span>
        </div>
      </div>

      {/* Content */}
      <div className="flex-1 overflow-auto p-4">
        {/* Main Navigation */}
        {baseNav.length > 0 && (
          <div className="mb-6">
            <h3
              className={cn(
                "px-2 text-xs font-semibold uppercase tracking-wide text-sidebar-foreground/70 transition-all duration-300 ease-in-out will-change-[opacity,height]",
                isOpen ? "mb-2 opacity-100 h-auto" : "mb-0 opacity-0 h-0 overflow-hidden"
              )}
              aria-hidden={!isOpen}
            >
              {ft("groups.main", "Menu Utama")}
            </h3>
            <nav className="space-y-1">
              {baseNav.map((item) => (
                <NavLink
                  key={item.to}
                  item={item}
                  isActive={pathname === item.to}
                  t={t}
                  collapsed={!isOpen}
                />
              ))}
            </nav>
          </div>
        )}

        {/* Admin Navigation */}
        {adminNav.length > 0 && (
          <div className="mb-6">
            <h3
              className={cn(
                "px-2 text-xs font-semibold uppercase tracking-wide text-sidebar-foreground/70 transition-all duration-300 ease-in-out will-change-[opacity,height]",
                isOpen ? "mb-2 opacity-100 h-auto" : "mb-0 opacity-0 h-0 overflow-hidden"
              )}
              aria-hidden={!isOpen}
            >
              {ft("groups.admin", "Admin")}
            </h3>
            <nav className="space-y-1">
              {adminNav.map((item) => (
                <NavLink
                  key={item.to}
                  item={item}
                  isActive={pathname === item.to}
                  t={t}
                  collapsed={!isOpen}
                />
              ))}
            </nav>
          </div>
        )}
      </div>

      {/* Footer */}
      <div className={cn(
        "border-t transition-all duration-300 ease-in-out",
        isOpen ? "p-4" : "p-2"
      )}>
        <Button
          variant="ghost"
          className={cn(
            "mb-2 w-full transition-all duration-300 ease-in-out",
            isOpen ? "justify-start" : "justify-center px-0"
          )}
          onClick={openSettingsModal}
          aria-label={ft("actions.openSettings", "Buka Pengaturan")}
          title={ft("actions.openSettings", "Buka Pengaturan")}
        >
          <Icon name="Settings" className={cn(
            "transition-all duration-300 ease-in-out",
            isOpen ? "h-4 w-4 mr-2" : "h-5 w-5"
          )} />
          <span
            className={cn(
              "truncate transition-all duration-300 ease-in-out will-change-[opacity,width]",
              isOpen ? "opacity-100 w-auto" : "opacity-0 w-0 overflow-hidden"
            )}
            aria-hidden={!isOpen}
          >
            {ft("actions.openSettings", "Buka Pengaturan")}
          </span>
        </Button>

        {user ? (
          <div className={cn(
            "transition-all duration-300 ease-in-out",
            isOpen ? "space-y-2" : "space-y-0"
          )}>
            {isOpen ? (
              <div className="flex items-center gap-2 rounded-lg bg-sidebar-accent p-2">
                <div className="flex h-8 w-8 items-center justify-center rounded-lg bg-primary text-primary-foreground text-sm">
                  {initials}
                </div>
                <div className="flex-1 text-sm">
                  <div className="font-semibold truncate">{displayName}</div>
                </div>
              </div>
            ) : (
              <div className="flex items-center justify-center">
                <div className="flex h-8 w-8 items-center justify-center rounded-lg bg-primary text-primary-foreground text-sm">
                  {initials}
                </div>
              </div>
            )}
            <Button
              variant="ghost"
              size="sm"
              className={cn(
                "w-full transition-all duration-300 ease-in-out",
                isOpen ? "justify-start" : "justify-center px-0"
              )}
              onClick={logout}
              aria-label={t("avatar.menu.logout", "Sign out")}
              title={t("avatar.menu.logout", "Sign out")}
            >
              <Icon name="LogOut" className={cn(
                "transition-all duration-300 ease-in-out",
                isOpen ? "h-4 w-4 mr-2" : "h-5 w-5"
              )} />
              <span
                className={cn(
                  "truncate transition-all duration-300 ease-in-out will-change-[opacity,width]",
                  isOpen ? "opacity-100 w-auto" : "opacity-0 w-0 overflow-hidden"
                )}
                aria-hidden={!isOpen}
              >
                {t("avatar.menu.logout", "Sign out")}
              </span>
            </Button>
          </div>
        ) : (
          <Button
            variant="ghost"
            size="sm"
            className={cn(
              "w-full transition-all duration-300 ease-in-out",
              isOpen ? "justify-start" : "justify-center px-0"
            )}
            onClick={() => openModal()}
            aria-label={t("avatar.menu.login", "Sign in")}
            title={t("avatar.menu.login", "Sign in")}
          >
            <Icon name="LogIn" className={cn(
            "transition-all duration-300 ease-in-out",
            isOpen ? "h-4 w-4 mr-2" : "h-5 w-5"
          )} />
            <span
              className={cn(
                "truncate transition-all duration-300 ease-in-out will-change-[opacity,width]",
                isOpen ? "opacity-100 w-auto" : "opacity-0 w-0 overflow-hidden"
              )}
              aria-hidden={!isOpen}
            >
              {t("avatar.menu.login", "Sign in")}
            </span>
          </Button>
        )}
      </div>
    </div>
    </>
  );
}

interface NavLinkProps {
  item: NavItem;
  isActive: boolean;
  t: (key: string, fallback?: string, values?: Record<string, unknown>) => string;
  collapsed: boolean;
}

function NavLink({ item, isActive, t, collapsed }: NavLinkProps) {
  const { setIsOpen, isMobile } = useSidebar();
  const label = t(item.labelKey || "", item.labelFallback || item.name);
  
  // Auto-close sidebar on mobile when clicking a link
  const handleClick = () => {
    if (isMobile) {
      setIsOpen(false);
    }
  };

  if (isExternalLink(item.to)) {
    return (
      <a
        href={item.to}
        target="_blank"
        rel="noopener noreferrer"
        onClick={handleClick}
        className={cn(
          "flex items-center rounded-lg px-2 py-2 text-sm transition-all duration-300 ease-in-out",
          "hover:bg-sidebar-accent hover:text-sidebar-accent-foreground",
          isActive && "bg-sidebar-accent text-sidebar-accent-foreground",
          collapsed ? "justify-center px-0 gap-0" : "gap-2"
        )}
      >
        <Icon name={item.icon} className={cn("transition-all", collapsed ? "h-6 w-6" : "h-4 w-4") } />
        <span
          className={cn(
            "truncate transition-all duration-300 ease-in-out will-change-[opacity,width]",
            collapsed ? "opacity-0 w-0 overflow-hidden" : "opacity-100 w-auto"
          )}
          aria-hidden={collapsed}
        >
          {label}
        </span>
      </a>
    );
  }

  return (
    <Link
      href={item.to}
      onClick={handleClick}
      className={cn(
        "flex items-center rounded-lg px-2 py-2 text-sm transition-all duration-300 ease-in-out",
        "hover:bg-sidebar-accent hover:text-sidebar-accent-foreground",
        isActive && "bg-sidebar-accent text-sidebar-accent-foreground",
        collapsed ? "justify-center px-0 gap-0" : "gap-2"
      )}
    >
      <Icon name={item.icon} className={cn("transition-all", collapsed ? "h-6 w-6" : "h-4 w-4") } />
      <span
        className={cn(
          "truncate transition-all duration-300 ease-in-out will-change-[opacity,width]",
          collapsed ? "opacity-0 w-0 overflow-hidden" : "opacity-100 w-auto"
        )}
        aria-hidden={collapsed}
      >
        {label}
      </span>
    </Link>
  );
}
