// FunMeter/frontend/components/layout/HeaderBar.tsx
// components/layout/HeaderBar.tsx
// Port dari src-vue-original/components/HeaderBar.vue

"use client";

import React, { useEffect, useRef } from "react";
import Link from "next/link";
import { usePathname } from "next/navigation";
import { useI18n } from "@/components/providers/I18nProvider";
import { Icon } from "@/components/common/Icon";
import { SidebarTrigger } from "@/components/ui/sidebar";
import { cn } from "@/lib/utils";
import { useTheme } from "@/components/providers/ThemeProvider";

interface HeaderBarProps {
  hidden?: boolean;
  onHeightChange?: (height: number) => void;
}

// Route metadata untuk title dan breadcrumb
const routeMetadata: Record<string, { titleKey?: string; titleFallback?: string; navKey?: string; navFallback?: string }> = {
  "/home": {
    titleKey: "pages.attendanceFunMeter.title",
    titleFallback: "Face Recognition",
    navKey: "nav.attendanceFunMeter",
    navFallback: "Pengenalan Wajah",
  },
  "/attendance": {
    titleKey: "pages.attendance.title",
    titleFallback: "Attendance",
    navKey: "nav.attendance",
    navFallback: "Absensi",
  },
  "/fun-meter": {
    titleKey: "pages.funMeter.title",
    titleFallback: "Fun Meter",
    navKey: "nav.funMeter",
    navFallback: "Fun Meter",
  },
  "/absensi-fun-meter": {
    titleKey: "pages.attendanceFunMeter.title",
    titleFallback: "attendance Fun Meter",
    navKey: "nav.attendanceFunMeter",
    navFallback: "Absensi Fun Meter",
  },
  "/register-face": {
    titleKey: "pages.registerFace.title",
    titleFallback: "Daftar Wajah",
    navKey: "nav.registerFace",
    navFallback: "Daftar Wajah",
  },
  "/admin/dashboard": {
    titleKey: "pages.adminDashboard.title",
    titleFallback: "Dashboard Admin",
    navKey: "nav.adminDashboard",
    navFallback: "Dashboard Admin",
  },
  "/admin/list-members": {
    titleKey: "pages.adminRegisterDb.title",
    titleFallback: "DB Wajah Admin",
    navKey: "nav.adminRegisterDb",
    navFallback: "DB Wajah Admin",
  },
  "/admin/schedule": {
    titleKey: "pages.adminSchedule.title",
    titleFallback: "Jadwal Admin",
    navKey: "nav.adminSchedule",
    navFallback: "Jadwal Admin",
  },
  "/admin/attendance": {
    titleKey: "pages.adminAttendance.title",
    titleFallback: "Absensi Admin",
    navKey: "nav.adminAttendance",
    navFallback: "Absensi Admin",
  },
  "/admin/attendance-summary": {
    titleKey: "pages.adminAttendanceSummary.title",
    titleFallback: "Ringkasan Absensi",
    navKey: "nav.adminAttendanceSummary",
    navFallback: "Ringkasan Absensi",
  },
  "/admin/users": {
    titleKey: "pages.adminUsers.title",
    titleFallback: "Manajemen Pengguna",
    navKey: "nav.adminUsers",
    navFallback: "Manajemen Pengguna",
  },
  "/admin/config": {
    titleKey: "pages.adminConfig.title",
    titleFallback: "Konfigurasi Sistem",
    navKey: "nav.adminConfig",
    navFallback: "Konfigurasi Sistem",
  },
  "/admin/advertisement": {
    titleKey: "pages.adminAdvertisement.title",
    titleFallback: "Advertisement",
    navKey: "nav.adminAdvertisement",
    navFallback: "Advertisement",
  },
};

export function HeaderBar({ hidden = false, onHeightChange }: HeaderBarProps) {
  const pathname = usePathname();
  const { t } = useI18n();
  const headerRef = useRef<HTMLDivElement>(null);
  const { isDark, toggleTheme } = useTheme();

  // Measure header height
  useEffect(() => {
    const measure = () => {
      const height = headerRef.current?.getBoundingClientRect()?.height;
      if (height && onHeightChange) {
        onHeightChange(Math.round(height));
      }
    };

    measure();
    window.addEventListener("resize", measure);
    return () => window.removeEventListener("resize", measure);
  }, [onHeightChange]);

  // Get breadcrumb
  const crumb = pathname.startsWith("/admin") 
    ? t("header.breadcrumb.admin", "Admin")
    : t("header.breadcrumb.website", "Website");

  // Get page title
  const meta = routeMetadata[pathname] || {};
  const titleKey = meta.titleKey || meta.navKey;
  const titleFallback = meta.titleFallback || meta.navFallback || t("header.title.default", "Pengenalan Wajah");
  const title = titleKey ? t(titleKey, titleFallback) : titleFallback;

  const headerClass = cn(
    "sticky top-0 z-40 border-b bg-background/80 backdrop-blur supports-[backdrop-filter]:bg-background/60 transition-all",
    hidden ? "-translate-y-full opacity-0" : "translate-y-0 opacity-100"
  );

  return (
    <div ref={headerRef} className={headerClass}>
      <div className="flex h-14 items-center gap-2 px-3 sm:h-16 sm:px-4">
        {/* Mobile trigger */}
        <SidebarTrigger 
          className="inline-flex lg:hidden"
          aria-label={t("header.actions.openNavigation", "Buka navigasi")}
        />

        {/* Desktop trigger */}
        <div className="hidden items-center lg:flex">
          <SidebarTrigger />
        </div>

        {/* Breadcrumb + Title */}
        <div className="min-w-0">
          <p className="text-[11px] uppercase tracking-widest text-muted-foreground">
            {crumb}
          </p>
          <h1 className="truncate text-base font-semibold sm:text-lg">
            {title}
          </h1>
        </div>

        <div className="ml-auto flex items-center gap-2">
          <Link
            href="/"
            className="inline-flex items-center gap-2 rounded-md border px-2 py-1.5 text-xs font-medium hover:bg-accent hover:text-accent-foreground sm:px-2.5"
          >
            <Icon name="Radio" className="h-3.5 w-3.5 sm:h-4 sm:w-4" />
            <span className="hidden xs:inline sm:inline">{t("header.actions.live", "Langsung")}</span>
          </Link>
        </div>
      </div>
    </div>
  );
}

// FunMeter/FaceRecognition/src-vue-original/components/HeaderBar.vue
<script setup lang="ts">
import { computed, inject, onMounted, ref, watch } from "vue";
import { useRoute, RouterLink } from "vue-router";
import { SidebarTrigger } from "@/components/ui/sidebar";
import { useI18n } from "@/i18n";
import Icon from "@/components/Icon.vue";

const props = defineProps({
  hidden: { type: Boolean, default: false },
  left: { type: Number, default: 0 },
  transStyle: { type: Object, default: () => ({}) },
});
const emit = defineEmits(["height"]);
const { t } = useI18n();

const route = useRoute();

const headerEl = ref<HTMLElement | null>(null);
function measure() {
  const h = headerEl.value?.getBoundingClientRect()?.height;
  if (h) emit("height", Math.round(h));
}
onMounted(measure);
watch(() => props.left, measure);

const headerClass = computed(() => (props.hidden ? "-translate-y-full opacity-0" : "translate-y-0 opacity-100"));

const crumb = computed(() => {
  if (route.path.startsWith("/admin")) return t("header.breadcrumb.admin", "Admin");
  return t("header.breadcrumb.website", "Situs");
});

const title = computed(() => {
  const m: any = route.meta || {};
  const key = m.titleKey || m.navKey;
  const fb = m.titleFallback || m.navFallback || route.name || t("header.title.default", "Pengenalan Wajah");
  return t(key, fb) ?? String(fb);
});
</script>

<template>
  <div
    ref="headerEl"
    class="sticky top-0 z-40 border-b bg-background/80 backdrop-blur supports-[backdrop-filter]:bg-background/60 transition-all"
    :class="headerClass"
    :style="[{ left: props.left + 'px', right: '0px' }, props.transStyle]">
    <div class="flex h-14 items-center gap-2 px-3 sm:h-16 sm:px-4">
      <!-- Mobile trigger langsung ke SidebarProvider -->
      <SidebarTrigger
        class="inline-flex lg:hidden"
        :aria-label="t('header.actions.openNavigation', 'Buka navigasi')" />

      <!-- Desktop trigger / custom slot kiri -->
      <div class="hidden items-center lg:flex">
        <slot name="left">
          <SidebarTrigger />
        </slot>
      </div>

      <!-- Breadcrumb + Title -->
      <div class="min-w-0">
        <p class="text-[11px] uppercase tracking-widest text-muted-foreground">
          {{ crumb }}
        </p>
        <h1 class="truncate text-base font-semibold sm:text-lg">
          {{ title }}
        </h1>
      </div>

      <!-- Actions -->
      <div class="ml-auto flex items-center gap-2">
        <RouterLink
          to="/absensi-fun-meter"
          class="hidden sm:inline-flex items-center gap-2 rounded-md border px-2.5 py-1.5 text-xs font-medium hover:bg-accent hover:text-accent-foreground">
          <Icon name="Radio" class="h-4 w-4" />
          <span>{{ t("header.actions.live", "Langsung") }}</span>
        </RouterLink>
      </div>
    </div>
  </div>
</template>
